import { Component, OnInit } from '@angular/core';
import { Item } from '../item.model';

@Component({
  selector: 'app-item-list',
  templateUrl: './item-list.component.html',
  styleUrls: ['./item-list.component.scss']
})
export class ItemListComponent implements OnInit {

  items: Item[] = [
    {
      ItemId: 1,
  ItemName: 'DVD',
  CreatedOnDate: new Date(),
  Owner: 1,
  LentOut: false,
  LentTo: '',
  CanBeBorrowed: true,
  BorrowedDate: new Date(),
  ReturnDate: new Date(),
  image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },
    {
      ItemId: 3,
      ItemName: 'Board Game',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Gary',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1523875194681-bedd468c58bf?ixlib=rb-1.2.1&auto=format&fit=crop&w=1502&q=80"
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1501003878151-d3cb87799705?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1530328411047-7063dbd29029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1530328411047-7063dbd29029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80"
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1530328411047-7063dbd29029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1530328411047-7063dbd29029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1501003878151-d3cb87799705?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1530328411047-7063dbd29029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1530328411047-7063dbd29029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1530328411047-7063dbd29029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80",
    },
    {
      ItemId: 2,
      ItemName: 'book',
      CreatedOnDate: new Date(),
      Owner: 1,
      LentOut: true,
      LentTo: 'Greg',
      CanBeBorrowed: true,
      BorrowedDate: new Date(),
      ReturnDate: new Date(),
      image: "https://images.unsplash.com/photo-1530328411047-7063dbd29029?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80"
    },
  ];

  constructor() { }

  ngOnInit() {
  }

}
